# Generated by Django 6.0.2 on 2026-02-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumniprofile',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
