# Generated by Django 6.0.2 on 2026-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_approved_alumniprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
