# Generated by Django 6.0.2 on 2026-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alumniprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
