# Generated by Django 6.0.2 on 2026-02-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_alumniprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
